stages:
  - build

.build_all_examples: &build_all_examples |
  cd 1_hello_world
  idf.py build
  cd ../
  cd 2_drivers
  idf.py build
  cd ../
  cd 3_wifi_connection
  idf.py build
  cd ../
  cd 4_network_config
  idf.py build
  cd ../
  cd 5_cloud
  touch main/cloud_cfg/server.cert main/cloud_cfg/device.cert main/cloud_cfg/device.key main/cloud_cfg/deviceid.txt main/cloud_cfg/endpoint.txt
  idf.py build
  cd ../
  cd 6_ota
  touch main/cloud_cfg/server.cert main/cloud_cfg/device.cert main/cloud_cfg/device.key main/cloud_cfg/deviceid.txt main/cloud_cfg/endpoint.txt
  idf.py build
  cd ../
  cd 7_mfg
  touch main/cloud_cfg/server.cert main/cloud_cfg/device.cert main/cloud_cfg/device.key main/cloud_cfg/deviceid.txt main/cloud_cfg/endpoint.txt
  idf.py build

.fetch_aws_iot: &fetch_aws_iot |
  git submodule update --init --recursive

.build_template:
  stage: build
  image: espressif/idf:latest
  tags:
    - build
    - internet
  variables:
    PEDANTIC_FLAGS: "-Werror -Werror=deprecated-declarations -Werror=unused-variable -Werror=unused-but-set-variable -Werror=unused-function"
    EXTRA_CFLAGS: "${PEDANTIC_FLAGS}"
    EXTRA_CXXFLAGS: "${PEDANTIC_FLAGS}"
  script:
    - *fetch_aws_iot
    - *build_all_examples

build_idf_v4.1:
  extends: .build_template
  image: espressif/idf:release-v4.1

build_idf_v4.2:
  extends: .build_template
  image: espressif/idf:release-v4.2

build_idf_v4.3:
  extends: .build_template
  image: espressif/idf:release-v4.3

build_idf_v4.4:
  extends: .build_template
  image: espressif/idf:release-v4.4

build_idf_master:
  extends: .build_template
  image: espressif/idf:latest
